# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/user
Accept: application/json

###

GET http://localhost:8080/finduser/
Accept: application/json

###
POST http://localhost:8080/adduser
Content-Type: application/json

{
  "username": "user111",
  "email": "user111@dgsw",
  "pw": "111"
}

###
PUT http://localhost:8080/updateuser/1
Content-Type: application/json

{
  "filename": "코카콜라.PNG",
  "filepath": "D:/Web_Code/20190326/upload/0eaa9a5e-f39b-4759-9fc0-ea4e90b1bd33_코카콜라.PNG"
}

###

DELETE http://localhost:8080/deleteuser/65

###

GET http://localhost:8080/listcomment
Accept: application/json

###

GET http://localhost:8080/comment
Accept: application/json

###

POST http://localhost:8080//addcomment
Content-Type: application/json

{
   "userId": 1,
   "content": "hello world"
}

###

DELETE http://localhost:8080/deletecomment/16

###

GET http://localhost:8080/attachment/1

###